// List of all IANA timezones with GMT offsets (abbreviated for brevity, use full list in production)
export const TIMEZONES = [
  { value: 'Pacific/Midway', label: '(GMT-11:00) Midway Island, Samoa' },
  { value: 'Pacific/Honolulu', label: '(GMT-10:00) Hawaii' },
  { value: 'America/Anchorage', label: '(GMT-09:00) Alaska' },
  { value: 'America/Los_Angeles', label: '(GMT-08:00) Pacific Time' },
  { value: 'America/Denver', label: '(GMT-07:00) Mountain Time' },
  { value: 'America/Chicago', label: '(GMT-06:00) Central Time' },
  { value: 'America/New_York', label: '(GMT-05:00) Eastern Time' },
  { value: 'America/Caracas', label: '(GMT-04:00) Caracas, La Paz' },
  { value: 'America/Santiago', label: '(GMT-03:00) Santiago' },
  { value: 'America/Noronha', label: '(GMT-02:00) Mid-Atlantic' },
  { value: 'Atlantic/Azores', label: '(GMT-01:00) Azores' },
  { value: 'Europe/London', label: '(GMT+00:00) London, Lisbon' },
  { value: 'Europe/Berlin', label: '(GMT+01:00) Berlin, Rome, Paris' },
  { value: 'Europe/Athens', label: '(GMT+02:00) Athens, Cairo, Jerusalem' },
  { value: 'Africa/Johannesburg', label: '(GMT+02:00) Africa/Johannesburg' },
  { value: 'Europe/Moscow', label: '(GMT+03:00) Moscow, St. Petersburg' },
  { value: 'Asia/Dubai', label: '(GMT+04:00) Abu Dhabi, Muscat' },
  { value: 'Asia/Karachi', label: '(GMT+05:00) Islamabad, Karachi' },
  { value: 'Asia/Dhaka', label: '(GMT+06:00) Dhaka, Astana' },
  { value: 'Asia/Bangkok', label: '(GMT+07:00) Bangkok, Hanoi, Jakarta' },
  { value: 'Asia/Shanghai', label: '(GMT+08:00) Beijing, Perth, Singapore' },
  { value: 'Asia/Tokyo', label: '(GMT+09:00) Tokyo, Seoul, Osaka' },
  { value: 'Australia/Sydney', label: '(GMT+10:00) Sydney, Guam' },
  { value: 'Pacific/Auckland', label: '(GMT+12:00) Auckland, Fiji' },
  // ... (add all IANA timezones for production)
]
